#!/bin/bash

#Start
echo "Please input your log directory:"
year=`date +%Y`
month=`date +%m`
day=`date +%d`
#Test data.   year=2014 month=05 day=23
read $LOGPATH
echo $LOGPATH

#Should do something to handle if there is not data to the specified date.log!
if [ -d $LOGPATH ];then
	mkdir -p ${LOGPATH}/$year/$month/
	sed "/${year}-${month}-${day}/!d" ${LOGPATH}access.log > ${LOGPATH}/$year/$month/access_$year-$month-$day.log
	echo
	#cat ${LOGPATH}/$year/$month/access_$year-$month-$day.log
	echo "Have cut the log successfully!"
fi
