# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 10:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateTimeField()),
                ('genre', models.CharField(default='a', max_length=1)),
                ('number', models.IntegerField(default=1)),
                ('status', models.IntegerField(choices=[(1, 'BOOKED'), (2, 'BOUGHT'), (3, 'DISABLED')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TrainTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=4)),
                ('start', models.CharField(max_length=10)),
                ('terminus', models.CharField(max_length=10)),
                ('departure', models.DateTimeField()),
                ('last', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.TrainTicket'),
        ),
        migrations.AddField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
