# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 03:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=4)),
                ('start', models.CharField(max_length=10)),
                ('terminus', models.CharField(max_length=10)),
                ('departure', models.DateTimeField()),
                ('last', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BusTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateTimeField()),
                ('genre', models.CharField(choices=[('h', '\u786c\u5ea7'), ('s', '\u8f6f\u5ea7')], default='h', max_length=1)),
                ('number', models.IntegerField(default=1)),
                ('status', models.IntegerField(choices=[(1, 'BOOKED'), (2, 'BOUGHT'), (3, 'DISABLED')], default=1)),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.BusTicket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlyTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=6)),
                ('start', models.CharField(max_length=10)),
                ('terminus', models.CharField(max_length=10)),
                ('departure', models.DateTimeField()),
                ('last', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=1, max_digits=6)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FlyTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateTimeField()),
                ('genre', models.CharField(choices=[('h', '\u5934\u7b49\u8231'), ('c', '\u7ecf\u6d4e\u8231')], default='c', max_length=1)),
                ('number', models.IntegerField(default=1)),
                ('status', models.IntegerField(choices=[(1, 'BOOKED'), (2, 'BOUGHT'), (3, 'DISABLED')], default=1)),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.FlyTicket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateTimeField()),
                ('genre', models.CharField(choices=[('a', '\u6210\u4eba\u7968'), ('c', '\u513f\u7ae5\u7968'), ('h', '\u786c\u5ea7'), ('s', '\u5367\u94fa')], default='a', max_length=1)),
                ('number', models.IntegerField(default=1)),
                ('status', models.IntegerField(choices=[(1, 'BOOKED'), (2, 'BOUGHT'), (3, 'DISABLED')], default=1)),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.TrainTicket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='trade',
            name='serial',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='user',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
