# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20160302_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='bustrade',
            name='t_type',
            field=models.CharField(choices=[('a', '\u6210\u4eba\u7968'), ('s', '\u7279\u6b8a\u7968')], default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='flytrade',
            name='t_type',
            field=models.CharField(choices=[('w', '\u5168\u4ef7\u7968'), ('p', '\u7279\u4ef7\u7968')], default='w', max_length=1),
        ),
        migrations.AddField(
            model_name='traintrade',
            name='t_type',
            field=models.CharField(choices=[('a', '\u6210\u4eba\u7968'), ('c', '\u513f\u7ae5\u7968')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='bustrade',
            name='genre',
            field=models.CharField(choices=[('h', '\u786c\u5ea7'), ('u', '\u8f6f\u5ea7')], default='h', max_length=1),
        ),
        migrations.AlterField(
            model_name='flytrade',
            name='genre',
            field=models.CharField(choices=[('f', '\u5934\u7b49\u8231'), ('e', '\u7ecf\u6d4e\u8231')], default='c', max_length=1),
        ),
        migrations.AlterField(
            model_name='traintrade',
            name='genre',
            field=models.CharField(choices=[('h', '\u786c\u5ea7'), ('s', '\u5367\u94fa')], default='h', max_length=1),
        ),
    ]
