# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 08:13
from __future__ import unicode_literals

import Profile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='/home/seven/Code/DjangoProjects/TicketManagementSystem/static/images/1.jpg', height_field='avatar_height', upload_to=Profile.models.user_avatar_path, width_field='avatar_width')),
                ('avatar_height', models.PositiveIntegerField(blank=True, default=0)),
                ('avatar_width', models.PositiveIntegerField(blank=True, default=0)),
                ('phone_number', models.CharField(max_length=11, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
