# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 03:52
from __future__ import unicode_literals

import Profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20160304_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/home/seven/Code/DjangoProjects/TicketManagementSystem/media/mascot.png', height_field='avatar_height', upload_to=Profile.models.user_avatar_path, width_field='avatar_width'),
        ),
    ]
